export const categories = [
  { label: "Household", value: "household" },
  { label: "Electronics", value: "electronics" },
  { label: "Garden", value: "garden" },
  { label: "Sports", value: "sports" },
  { label: "Clothes", value: "clothes" },
  { label: "Tools", value: "tools" },
  { label: "Events", value: "events" },
  { label: "Books", value: "books" },
  { label: "Furniture", value: "furniture" },
  { label: "Baby & Kids", value: "baby_kids" },
  { label: "Automotive", value: "automotive" },
];

export const items = [
  // Household items
  { label: "Vacuum Cleaner", value: "vacuum_cleaner", category: "household" },
  { label: "Iron", value: "iron", category: "household" },
  { label: "Blender", value: "blender", category: "household" },
  { label: "Microwave", value: "microwave", category: "household" },
  { label: "Coffee Maker", value: "coffee_maker", category: "household" },
  { label: "Washing Machine", value: "washing_machine", category: "household" },
  { label: "Dryer", value: "dryer", category: "household" },
  { label: "Refrigerator", value: "refrigerator", category: "household" },
  { label: "Freezer", value: "freezer", category: "household" },
  { label: "Air Conditioner", value: "air_conditioner", category: "household" },
  { label: "Heater", value: "heater", category: "household" },
  { label: "Fan", value: "fan", category: "household" },
  { label: "Humidifier", value: "humidifier", category: "household" },
  { label: "Dehumidifier", value: "dehumidifier", category: "household" },
  { label: "Dishes Set", value: "dishes_set", category: "household" },
  { label: "Cooking Pots", value: "cooking_pots", category: "household" },
  { label: "Pressure Cooker", value: "pressure_cooker", category: "household" },
  { label: "Air Fryer", value: "air_fryer", category: "household" },
  { label: "Food Processor", value: "food_processor", category: "household" },
  { label: "Toaster", value: "toaster", category: "household" },
  { label: "Kettle", value: "kettle", category: "household" },
  { label: "Rice Cooker", value: "rice_cooker", category: "household" },
  { label: "Mixer", value: "mixer", category: "household" },
  { label: "Juicer", value: "juicer", category: "household" },
  { label: "Slow Cooker", value: "slow_cooker", category: "household" },
  { label: "Dishwasher", value: "dishwasher", category: "household" },
  { label: "Oven", value: "oven", category: "household" },
  { label: "Stove", value: "stove", category: "household" },
  { label: "Steam Cleaner", value: "steam_cleaner", category: "household" },
  { label: "Carpet Cleaner", value: "carpet_cleaner", category: "household" },

  // Electronics
  { label: "Laptop", value: "laptop", category: "electronics" },
  { label: "Desktop Computer", value: "desktop_computer", category: "electronics" },
  { label: "iPad/Tablet", value: "tablet", category: "electronics" },
  { label: "Monitor", value: "monitor", category: "electronics" },
  { label: "Printer", value: "printer", category: "electronics" },
  { label: "Scanner", value: "scanner", category: "electronics" },
  { label: "Camera", value: "camera", category: "electronics" },
  { label: "Video Camera", value: "video_camera", category: "electronics" },
  { label: "GoPro/Action Camera", value: "action_camera", category: "electronics" },
  { label: "Television", value: "television", category: "electronics" },
  { label: "Speakers", value: "speakers", category: "electronics" },
  { label: "Gaming Console", value: "gaming_console", category: "electronics" },
  { label: "VR Headset", value: "vr_headset", category: "electronics" },
  { label: "Projector", value: "projector", category: "electronics" },
  { label: "Phone Charger", value: "phone_charger", category: "electronics" },
  { label: "Power Bank", value: "power_bank", category: "electronics" },
  { label: "Router", value: "router", category: "electronics" },
  { label: "External Hard Drive", value: "external_hard_drive", category: "electronics" },
  { label: "Keyboard", value: "keyboard", category: "electronics" },
  { label: "Mouse", value: "mouse", category: "electronics" },
  { label: "Webcam", value: "webcam", category: "electronics" },
  { label: "Smart Watch", value: "smart_watch", category: "electronics" },

  // Garden
  { label: "Lawnmower", value: "lawnmower", category: "garden" },
  { label: "Electric Lawnmower", value: "electric_lawnmower", category: "garden" },
  { label: "Garden Hose", value: "garden_hose", category: "garden" },
  { label: "Hedge Trimmer", value: "hedge_trimmer", category: "garden" },
  { label: "Chainsaw", value: "chainsaw", category: "garden" },
  { label: "Shovel", value: "shovel", category: "garden" },
  { label: "Rake", value: "rake", category: "garden" },
  { label: "Wheelbarrow", value: "wheelbarrow", category: "garden" },
  { label: "Pruning Shears", value: "pruning_shears", category: "garden" },
  { label: "Watering Can", value: "watering_can", category: "garden" },
  { label: "Garden Tools Set", value: "garden_tools_set", category: "garden" },
  { label: "Leaf Blower", value: "leaf_blower", category: "garden" },
  { label: "Plant Pots", value: "plant_pots", category: "garden" },
  { label: "Planter Boxes", value: "planter_boxes", category: "garden" },
  { label: "Garden Sprinkler", value: "garden_sprinkler", category: "garden" },
  { label: "Pressure Washer", value: "pressure_washer", category: "garden" },
  { label: "Garden Furniture", value: "garden_furniture", category: "garden" },
  { label: "BBQ Grill", value: "bbq_grill", category: "garden" },
  { label: "Patio Heater", value: "patio_heater", category: "garden" },

  // Sports
  { label: "Football", value: "football", category: "sports" },
  { label: "Basketball", value: "basketball", category: "sports" },
  { label: "Volleyball", value: "volleyball", category: "sports" },
  { label: "Tennis Racket", value: "tennis_racket", category: "sports" },
  { label: "Badminton Set", value: "badminton_set", category: "sports" },
  { label: "Bicycle", value: "bicycle", category: "sports" },
  { label: "Mountain Bike", value: "mountain_bike", category: "sports" },
  { label: "Electric Bike", value: "electric_bike", category: "sports" },
  { label: "Scooter", value: "scooter", category: "sports" },
  { label: "Skateboard", value: "skateboard", category: "sports" },
  { label: "Treadmill", value: "treadmill", category: "sports" },
  { label: "Dumbbells", value: "dumbbells", category: "sports" },
  { label: "Weight Bench", value: "weight_bench", category: "sports" },
  { label: "Swimming Goggles", value: "swimming_goggles", category: "sports" },
  { label: "Snorkeling Set", value: "snorkeling_set", category: "sports" },
  { label: "Tennis Table", value: "tennis_table", category: "sports" },
  { label: "Foosball Table", value: "foosball_table", category: "sports" },
  { label: "Pool Table", value: "pool_table", category: "sports" },
  { label: "Exercise Bike", value: "exercise_bike", category: "sports" },
  { label: "Elliptical Machine", value: "elliptical_machine", category: "sports" },
  { label: "Rowing Machine", value: "rowing_machine", category: "sports" },
  { label: "Golf Clubs", value: "golf_clubs", category: "sports" },
  { label: "Camping Tent", value: "camping_tent", category: "sports" },
  { label: "Sleeping Bag", value: "sleeping_bag", category: "sports" },
  { label: "Backpack", value: "backpack", category: "sports" },
  { label: "Hiking Boots", value: "hiking_boots", category: "sports" },
  { label: "Fishing Rod", value: "fishing_rod", category: "sports" },
  { label: "Kayak", value: "kayak", category: "sports" },
  { label: "Stand-up Paddleboard", value: "paddleboard", category: "sports" },

  // Clothes
  { label: "Winter Coat", value: "winter_coat", category: "clothes" },
  { label: "Leather Jacket", value: "leather_jacket", category: "clothes" },
  { label: "Formal Suit", value: "formal_suit", category: "clothes" },
  { label: "Evening Dress", value: "evening_dress", category: "clothes" },
  { label: "Traditional Dress", value: "traditional_dress", category: "clothes" },
  { label: "Thobe", value: "thobe", category: "clothes" },
  { label: "Abaya", value: "abaya", category: "clothes" },
  { label: "Winter Boots", value: "winter_boots", category: "clothes" },
  { label: "Formal Shoes", value: "formal_shoes", category: "clothes" },
  { label: "Handbag", value: "handbag", category: "clothes" },
  { label: "Suitcase", value: "suitcase", category: "clothes" },
  { label: "Wedding Dress", value: "wedding_dress", category: "clothes" },
  { label: "Tuxedo", value: "tuxedo", category: "clothes" },
  { label: "Graduation Gown", value: "graduation_gown", category: "clothes" },
  { label: "Costume", value: "costume", category: "clothes" },
  { label: "Ski Suit", value: "ski_suit", category: "clothes" },

  // Tools
  { label: "Drill", value: "drill", category: "tools" },
  { label: "Impact Driver", value: "impact_driver", category: "tools" },
  { label: "Hammer", value: "hammer", category: "tools" },
  { label: "Screwdriver Set", value: "screwdriver_set", category: "tools" },
  { label: "Saw", value: "saw", category: "tools" },
  { label: "Circular Saw", value: "circular_saw", category: "tools" },
  { label: "Jigsaw", value: "jigsaw", category: "tools" },
  { label: "Ladder", value: "ladder", category: "tools" },
  { label: "Step Ladder", value: "step_ladder", category: "tools" },
  { label: "Extension Ladder", value: "extension_ladder", category: "tools" },
  { label: "Measuring Tape", value: "measuring_tape", category: "tools" },
  { label: "Wrench Set", value: "wrench_set", category: "tools" },
  { label: "Socket Set", value: "socket_set", category: "tools" },
  { label: "Level", value: "level", category: "tools" },
  { label: "Paint Brush Set", value: "paint_brush_set", category: "tools" },
  { label: "Paint Roller", value: "paint_roller", category: "tools" },
  { label: "Toolbox", value: "toolbox", category: "tools" },
  { label: "Electric Sander", value: "electric_sander", category: "tools" },
  { label: "Pliers", value: "pliers", category: "tools" },
  { label: "Wire Cutters", value: "wire_cutters", category: "tools" },
  { label: "Angle Grinder", value: "angle_grinder", category: "tools" },
  { label: "Welding Machine", value: "welding_machine", category: "tools" },
  { label: "Generator", value: "generator", category: "tools" },
  { label: "Air Compressor", value: "air_compressor", category: "tools" },
  { label: "Nail Gun", value: "nail_gun", category: "tools" },

  // Events
  { label: "Tables", value: "tables", category: "events" },
  { label: "Chairs", value: "chairs", category: "events" },
  { label: "Folding Chairs", value: "folding_chairs", category: "events" },
  { label: "Tent", value: "tent", category: "events" },
  { label: "Microphone", value: "microphone", category: "events" },
  { label: "Wireless Microphone", value: "wireless_microphone", category: "events" },
  { label: "Decorations", value: "decorations", category: "events" },
  { label: "Lighting Equipment", value: "lighting_equipment", category: "events" },
  { label: "LED Lights", value: "led_lights", category: "events" },
  { label: "Tablecloth", value: "tablecloth", category: "events" },
  { label: "Canopy", value: "canopy", category: "events" },
  { label: "Stage Equipment", value: "stage_equipment", category: "events" },
  { label: "Photo Booth", value: "photo_booth", category: "events" },
  { label: "Fog Machine", value: "fog_machine", category: "events" },
  { label: "Bubble Machine", value: "bubble_machine", category: "events" },
  { label: "Popcorn Machine", value: "popcorn_machine", category: "events" },
  { label: "Cotton Candy Machine", value: "cotton_candy_machine", category: "events" },
  { label: "Chocolate Fountain", value: "chocolate_fountain", category: "events" },
  { label: "Bouncy Castle", value: "bouncy_castle", category: "events" },

  // Books
  { label: "Textbooks", value: "textbooks", category: "books" },
  { label: "University Books", value: "university_books", category: "books" },
  { label: "Medical Books", value: "medical_books", category: "books" },
  { label: "Engineering Books", value: "engineering_books", category: "books" },
  { label: "Novels", value: "novels", category: "books" },
  { label: "Reference Books", value: "reference_books", category: "books" },
  { label: "Encyclopedia", value: "encyclopedia", category: "books" },
  { label: "Children's Books", value: "childrens_books", category: "books" },
  { label: "Cookbooks", value: "cookbooks", category: "books" },
  { label: "Technical Manuals", value: "technical_manuals", category: "books" },
  { label: "Art Books", value: "art_books", category: "books" },
  { label: "History Books", value: "history_books", category: "books" },
  { label: "Science Books", value: "science_books", category: "books" },
  { label: "Language Learning", value: "language_learning", category: "books" },
  { label: "Self-Help Books", value: "self_help_books", category: "books" },
  { label: "Business Books", value: "business_books", category: "books" },
  { label: "Poetry Books", value: "poetry_books", category: "books" },

  // Furniture
  { label: "Sofa", value: "sofa", category: "furniture" },
  { label: "Sectional Sofa", value: "sectional_sofa", category: "furniture" },
  { label: "Bed Frame", value: "bed_frame", category: "furniture" },
  { label: "Mattress", value: "mattress", category: "furniture" },
  { label: "Wardrobe", value: "wardrobe", category: "furniture" },
  { label: "Dining Table", value: "dining_table", category: "furniture" },
  { label: "Coffee Table", value: "coffee_table", category: "furniture" },
  { label: "TV Stand", value: "tv_stand", category: "furniture" },
  { label: "Bookshelf", value: "bookshelf", category: "furniture" },
  { label: "Desk", value: "desk", category: "furniture" },
  { label: "Office Chair", value: "office_chair", category: "furniture" },
  { label: "Dining Chairs", value: "dining_chairs", category: "furniture" },
  { label: "Dresser", value: "dresser", category: "furniture" },
  { label: "Nightstand", value: "nightstand", category: "furniture" },
  { label: "Cabinet", value: "cabinet", category: "furniture" },
  { label: "Shoe Rack", value: "shoe_rack", category: "furniture" },
  { label: "Mirror", value: "mirror", category: "furniture" },
  { label: "Chandelier", value: "chandelier", category: "furniture" },
  { label: "Floor Lamp", value: "floor_lamp", category: "furniture" },
  { label: "Curtains", value: "curtains", category: "furniture" },
  { label: "Rug", value: "rug", category: "furniture" },
  { label: "Carpet", value: "carpet", category: "furniture" },

  // Baby & Kids
  { label: "Stroller", value: "stroller", category: "baby_kids" },
  { label: "Baby Car Seat", value: "baby_car_seat", category: "baby_kids" },
  { label: "High Chair", value: "high_chair", category: "baby_kids" },
  { label: "Baby Crib", value: "baby_crib", category: "baby_kids" },
  { label: "Baby Monitor", value: "baby_monitor", category: "baby_kids" },
  { label: "Play Pen", value: "play_pen", category: "baby_kids" },
  { label: "Baby Swing", value: "baby_swing", category: "baby_kids" },
  { label: "Toys", value: "toys", category: "baby_kids" },
  { label: "Kids Bicycle", value: "kids_bicycle", category: "baby_kids" },
  { label: "Tricycle", value: "tricycle", category: "baby_kids" },
  { label: "Trampoline", value: "trampoline", category: "baby_kids" },
  { label: "Swing Set", value: "swing_set", category: "baby_kids" },

  // Automotive
  { label: "Car Jack", value: "car_jack", category: "automotive" },
  { label: "Jump Starter", value: "jump_starter", category: "automotive" },
  { label: "Tire Inflator", value: "tire_inflator", category: "automotive" },
  { label: "Car Vacuum", value: "car_vacuum", category: "automotive" },
  { label: "Car Polisher", value: "car_polisher", category: "automotive" },
  { label: "Roof Rack", value: "roof_rack", category: "automotive" },
  { label: "Bike Rack", value: "bike_rack", category: "automotive" },
  { label: "Car Cover", value: "car_cover", category: "automotive" },
  { label: "Dash Cam", value: "dash_cam", category: "automotive" },
  { label: "GPS Navigator", value: "gps_navigator", category: "automotive" },

];

export const cities = [
  { label: "Amman", value: "amman" },
  { label: "Zarqa", value: "zarqa" },
  { label: "Irbid", value: "irbid" },
  { label: "Aqaba", value: "aqaba" },
  { label: "Madaba", value: "madaba" },
  { label: "Salt", value: "salt" },
  { label: "Mafraq", value: "mafraq" },
  { label: "Jerash", value: "jerash" },
  { label: "Karak", value: "karak" },
  { label: "Tafilah", value: "tafilah" },
  { label: "Ma'an", value: "maan" },
  { label: "Ajloun", value: "ajloun" }
];

export const areas = [
    { label: "Abdoun Al Janobi (S)", value: "abdoun_al_janobi", city: "amman" },
  { label: "Abdoun Alshamali (N)", value: "abdoun_alshamali", city: "amman" },
  { label: "Abu Alanda", value: "abu_alanda", city: "amman" },
  { label: "Abu Alya", value: "abu_alya", city: "amman" },
  { label: "Abu Nsair", value: "abu_nsair", city: "amman" },
  { label: "Abu Sowaneh", value: "abu_sowaneh", city: "amman" },
  { label: "Ain Ghazal", value: "ain_ghazal", city: "amman" },
  { label: "Al Abdali", value: "al_abdali", city: "amman" },
  { label: "Al Abrar", value: "al_abrar", city: "amman" },
  { label: "Al Amal", value: "al_amal", city: "amman" },
  { label: "Al Amanah", value: "al_amanah", city: "amman" },
  { label: "Al Bnyat Al Shamali", value: "al_bnyat_al_shamali", city: "amman" },
  { label: "Al Bsha'Er", value: "al_bshaer", city: "amman" },
  { label: "Al Bunayyat Al Janubiyah", value: "al_bunayyat_al_janubiyah", city: "amman" },
  { label: "Al Dalelah", value: "al_dalelah", city: "amman" },
  { label: "Al Dia", value: "al_dia", city: "amman" },
  { label: "Al Dmenah", value: "al_dmenah", city: "amman" },
  { label: "Al Esra University", value: "al_esra_university", city: "amman" },
  { label: "Al Fadilah", value: "al_fadilah", city: "amman" },
  { label: "Al Faisaliah", value: "al_faisaliah", city: "amman" },
  { label: "Al Feisal", value: "al_feisal", city: "amman" },
  { label: "Al Ghrous", value: "al_ghrous", city: "amman" },
  { label: "Al Ghubaiyah", value: "al_ghubaiyah", city: "amman" },
  { label: "Al Hashmi Al Janoubi", value: "al_hashmi_al_janoubi", city: "amman" },
  { label: "Al Hashmi Al Shamali", value: "al_hashmi_al_shamali", city: "amman" },
  { label: "Al Hay Al Sharqi", value: "al_hay_al_sharqi", city: "amman" },
  { label: "Al Heri", value: "al_heri", city: "amman" },
  { label: "Al Hidayeh", value: "al_hidayeh", city: "amman" },
  { label: "Al Homar", value: "al_homar", city: "amman" },
  { label: "Al Horreyya", value: "al_horreyya", city: "amman" },
  { label: "Al Hraij", value: "al_hraij", city: "amman" },
  { label: "Al Husnyah", value: "al_husnyah", city: "amman" },
  { label: "AI Hussein Medical City", value: "al_hussein_medical_city", city: "amman" },
  { label: "Al Ihsan", value: "al_ihsan", city: "amman" },
  { label: "Al lman", value: "al_iman", city: "amman" },
  { label: "Al Jandweal", value: "al_jandweal", city: "amman" },
  { label: "Al Jizah", value: "al_jizah", city: "amman" },
  { label: "Al Jubeiha", value: "al_jubeiha", city: "amman" },
  { label: "Al Khaledin", value: "al_khaledin", city: "amman" },
  { label: "Al Khaznah", value: "al_khaznah", city: "amman" },
  { label: "Al Kolyah Aleslamyah", value: "al_kolyah_aleslamyah", city: "amman" },
  { label: "Al Kursi", value: "al_kursi", city: "amman" },
  { label: "Al Kutaifah", value: "al_kutaifah", city: "amman" },
  { label: "Al Lubban", value: "al_lubban", city: "amman" },
  { label: "Al Madenah Altebyah", value: "al_madenah_altebyah", city: "amman" },
  { label: "Al Madinah Al Riyadiah", value: "al_madinah_al_riyadiah", city: "amman" },
  { label: "Al Maghaba Al Sharqi", value: "al_maghaba_al_sharqi", city: "amman" },
  { label: "Al Mahattah", value: "al_mahattah", city: "amman" },
  { label: "Al Majd", value: "al_majd", city: "amman" },
  { label: "Al Mansour", value: "al_mansour", city: "amman" },
  { label: "Al Matabah", value: "al_matabah", city: "amman" },
  { label: "Al Mohajrean", value: "al_mohajrean", city: "amman" },
  { label: "Al Morouj", value: "al_morouj", city: "amman" },
  { label: "Al Mowahdin", value: "al_mowahdin", city: "amman" },
  { label: "Al Mowaqar", value: "al_mowaqar", city: "amman" },
  { label: "Al Muhajireen", value: "al_muhajireen", city: "amman" },
  { label: "Al Mushaqqar", value: "al_mushaqqar", city: "amman" },
  { label: "Al Muwaqqar", value: "al_muwaqqar", city: "amman" },
  { label: "Al Nuqairah", value: "al_nuqairah", city: "amman" },
  { label: "Al Ouroubah", value: "al_ouroubah", city: "amman" },
  { label: "Al Qastal", value: "al_qastal", city: "amman" },
  { label: "Al Qonaytrah", value: "al_qonaytrah", city: "amman" },
  { label: "Al Qweismeh", value: "al_qweismeh", city: "amman" },
  { label: "Al Rabaheya", value: "al_rabaheya", city: "amman" },
  { label: "Al Rabi", value: "al_rabi", city: "amman" },
  { label: "Al Rabwa", value: "al_rabwa", city: "amman" },
  { label: "Al Rahmaniah", value: "al_rahmaniah", city: "amman" },
  { label: "Al Raqim", value: "al_raqim", city: "amman" },
  { label: "Al Rawabi", value: "al_rawabi", city: "amman" },
  { label: "Al Rawdah", value: "al_rawdah", city: "amman" },
  { label: "Al Rawnaq", value: "al_rawnaq", city: "amman" },
  { label: "Al Rayyan", value: "al_rayyan", city: "amman" },
  { label: "Al Rewaq", value: "al_rewaq", city: "amman" },
  { label: "Al Rjoum", value: "al_rjoum", city: "amman" },
  { label: "Al Safa", value: "al_safa", city: "amman" },
  { label: "Al Salahyah", value: "al_salahyah", city: "amman" },
  { label: "Al Salam", value: "al_salam", city: "amman" },
  { label: "Al Salehien", value: "al_salehien", city: "amman" },
  { label: "Al Sayfiyah", value: "al_sayfiyah", city: "amman" },
  { label: "Al Sena'A", value: "al_senaa", city: "amman" },
  { label: "Al Shaheed Al Janobi", value: "al_shaheed_al_janobi", city: "amman" },
  { label: "Al Shaheed Al Shamali", value: "al_shaheed_al_shamali", city: "amman" },
  { label: "Al Swaisah", value: "al_swaisah", city: "amman" },
  { label: "Al Tajamouat Industrial City", value: "al_tajamouat_industrial_city", city: "amman" },
  { label: "Al Tatwir", value: "al_tatwir", city: "amman" },
  { label: "Al Thahir", value: "al_thahir", city: "amman" },
  { label: "Al Thra'", value: "al_thra", city: "amman" },
  { label: "AI Tla'A Al Sharqi", value: "al_tlaa_al_sharqi", city: "amman" },
  { label: "Al Wafa", value: "al_wafa", city: "amman" },
  { label: "Al Yadudah", value: "al_yadudah", city: "amman" },
  { label: "Al Yarmouk", value: "al_yarmouk", city: "amman" },
  { label: "Al Zaafaran", value: "al_zaafaran", city: "amman" },
  { label: "Al Zahra", value: "al_zahra", city: "amman" },
  { label: "Al'AI", value: "alai", city: "amman" },
  { label: "Al. Mansourah", value: "al_mansourah", city: "amman" },
  { label: "Alal", value: "alal", city: "amman" },
  { label: "Albasalah", value: "albasalah", city: "amman" },
  { label: "Albashayer", value: "albashayer", city: "amman" },
  { label: "Albnyat Aljanobi", value: "albnyat_aljanobi", city: "amman" },
  { label: "Aldeyar", value: "aldeyar", city: "amman" },
  { label: "Alfaroq", value: "alfaroq", city: "amman" },
  { label: "Alforosyah", value: "alforosyah", city: "amman" },
  { label: "Alforqan", value: "alforqan", city: "amman" },
  { label: "Alia Housing", value: "alia_housing", city: "amman" },
  { label: "Alkmalyah", value: "alkmalyah", city: "amman" },
  { label: "Alkoam Algharbi", value: "alkoam_algharbi", city: "amman" },
  { label: "Alkoam Alsharqi", value: "alkoam_alsharqi", city: "amman" },
  { label: "Alktaifah", value: "alktaifah", city: "amman" },
  { label: "Almahbah", value: "almahbah", city: "amman" },
  { label: "Algasbat", value: "algasbat", city: "amman" },
  { label: "Alqusur Al Malakiah", value: "alqusur_al_malakiah", city: "amman" },
  { label: "Alwehdat", value: "alwehdat", city: "amman" },
  { label: "Alyasmeen", value: "alyasmeen", city: "amman" },
  { label: "Alzaytonah", value: "alzaytonah", city: "amman" },
  { label: "Amman City Center", value: "amman_city_center", city: "amman" },
  { label: "Amman Mall", value: "amman_mall", city: "amman" },
  { label: "Applied Science University", value: "applied_science_university", city: "amman" },
  { label: "Arenbah Algharbyah", value: "arenbah_algharbyah", city: "amman" },
  { label: "Arenbah Alsharqyah", value: "arenbah_alsharqyah", city: "amman" },
  { label: "As Samik", value: "as_samik", city: "amman" },
  { label: "At Tunayb", value: "at_tunayb", city: "amman" },
  { label: "Ayn Rbat", value: "ayn_rbat", city: "amman" },
  { label: "Azzuhour", value: "azzuhour", city: "amman" },

  // Zarqa areas
  { label: "Zarqa City Center", value: "zarqa_center", city: "zarqa" },
  { label: "Al-Zarqa Al-Jadida", value: "al_zarqa_al_jadida", city: "zarqa" },
  { label: "Hay Al-Musleh", value: "hay_al_musleh", city: "zarqa" },
  { label: "Al-Falah", value: "al_falah", city: "zarqa" },
  { label: "Al-Hashemi", value: "al_hashemi_zarqa", city: "zarqa" },
  { label: "Al-Hashemi Al-Shamali", value: "al_hashemi_al_shamali", city: "zarqa" },
  { label: "Al-Hashemi Al-Janoubi", value: "al_hashemi_al_janoubi", city: "zarqa" },
  { label: "Al-Jazirah", value: "al_jazirah", city: "zarqa" },
  { label: "Russeifa", value: "russeifa", city: "zarqa" },
  { label: "Hay Nazzal", value: "hay_nazzal", city: "zarqa" },
  { label: "Azraq", value: "azraq", city: "zarqa" },
  { label: "Al-Dhulail", value: "al_dhulail", city: "zarqa" },

  // Irbid areas
  { label: "Irbid City Center", value: "irbid_center", city: "irbid" },
  { label: "Al-Hay Al-Sharqi", value: "al_hay_al_sharqi", city: "irbid" },
  { label: "Al-Hay Al-Gharbi", value: "al_hay_al_gharbi", city: "irbid" },
  { label: "Al-Hay Al-Janoubi", value: "al_hay_al_janoubi", city: "irbid" },
  { label: "Al-Husn", value: "al_husn", city: "irbid" },
  { label: "Ramtha", value: "ramtha", city: "irbid" },
  { label: "Sal", value: "sal", city: "irbid" },
  { label: "Hakama", value: "hakama", city: "irbid" },
  { label: "Al-Mazar", value: "al_mazar", city: "irbid" },
  { label: "Beit Ras", value: "beit_ras", city: "irbid" },
  { label: "Kufr Asad", value: "kufr_asad", city: "irbid" },
  { label: "University Street Irbid", value: "university_street_irbid", city: "irbid" },
  { label: "Princess Basma Street", value: "princess_basma_street", city: "irbid" },
  { label: "Al-Naseem", value: "al_naseem", city: "irbid" },

  // Aqaba areas
  { label: "Aqaba City Center", value: "aqaba_center", city: "aqaba" },
  { label: "Al-Sakinah", value: "al_sakinah", city: "aqaba" },
  { label: "Al-Nahda", value: "al_nahda", city: "aqaba" },
  { label: "Al-Rimal", value: "al_rimal", city: "aqaba" },
  { label: "Al-Mahdood", value: "al_mahdood", city: "aqaba" },
  { label: "Al-Hammamat", value: "al_hammamat", city: "aqaba" },
  { label: "Tala Bay", value: "tala_bay", city: "aqaba" },
  { label: "Ayla", value: "ayla", city: "aqaba" },
  { label: "South Beach", value: "south_beach", city: "aqaba" },
  { label: "Industrial Area", value: "industrial_area_aqaba", city: "aqaba" },

  // Salt areas
  { label: "Salt City Center", value: "salt_center", city: "salt" },
  { label: "Al-Ain Plaza", value: "al_ain_plaza", city: "salt" },
  { label: "Al-Jadiriyah", value: "al_jadiriyah", city: "salt" },
  { label: "Wadi Al-Akrad", value: "wadi_al_akrad", city: "salt" },
  { label: "Al-Salam", value: "al_salam_salt", city: "salt" },
  { label: "Zay", value: "zay", city: "salt" },
  { label: "Al-Akrad", value: "al_akrad", city: "salt" },

  // Madaba areas
  { label: "Madaba City Center", value: "madaba_center", city: "madaba" },
  { label: "Al-Nuzha", value: "al_nuzha", city: "madaba" },
  { label: "Al-Manshiyah", value: "al_manshiyah", city: "madaba" },
  { label: "Dhiban", value: "dhiban", city: "madaba" },
  { label: "Faisaliah", value: "faisaliah", city: "madaba" },
  { label: "Al-Yarmouk", value: "al_yarmouk_madaba", city: "madaba" },
  { label: "Main", value: "main", city: "madaba" },

  // Mafraq areas
  { label: "Mafraq City Center", value: "mafraq_center", city: "mafraq" },
  { label: "Al-Mafraq Al-Jadida", value: "al_mafraq_al_jadida", city: "mafraq" },
  { label: "Safawi", value: "safawi", city: "mafraq" },
  { label: "Ruwaished", value: "ruwaished", city: "mafraq" },
  { label: "Badia", value: "badia", city: "mafraq" },
  { label: "Al-Khalidiya", value: "al_khalidiya_mafraq", city: "mafraq" },

  // Jerash areas
  { label: "Jerash City Center", value: "jerash_center", city: "jerash" },
  { label: "Sakib", value: "sakib", city: "jerash" },
  { label: "Burma", value: "burma", city: "jerash" },
  { label: "Al-Kitteh", value: "al_kitteh", city: "jerash" },
  { label: "Souf", value: "souf", city: "jerash" },
  { label: "Raymoun", value: "raymoun", city: "jerash" },
  { label: "Mastaba", value: "mastaba", city: "jerash" },

  // Karak areas
  { label: "Karak City Center", value: "karak_center", city: "karak" },
  { label: "Mu'tah", value: "mutah", city: "karak" },
  { label: "Qasr", value: "qasr", city: "karak" },
  { label: "Al-Mazar Al-Janoubi", value: "al_mazar_al_janoubi", city: "karak" },
  { label: "Faqou'", value: "faqou", city: "karak" },
  { label: "Ghor Al-Safi", value: "ghor_al_safi", city: "karak" },
  { label: "Al-Rabba", value: "al_rabba", city: "karak" },

  // Ma'an areas
  { label: "Ma'an City Center", value: "maan_center", city: "maan" },
  { label: "Husseiniya", value: "husseiniya", city: "maan" },
  { label: "Shaubak", value: "shaubak", city: "maan" },
  { label: "Petra", value: "petra", city: "maan" },
  { label: "Wadi Musa", value: "wadi_musa", city: "maan" },
  { label: "Al-Jafr", value: "al_jafr", city: "maan" },
  { label: "Qadisiyah", value: "qadisiyah", city: "maan" },

  // Ajloun areas
  { label: "Ajloun City Center", value: "ajloun_center", city: "ajloun" },
  { label: "Sakhra", value: "sakhra", city: "ajloun" },
  { label: "Anjara", value: "anjara", city: "ajloun" },
  { label: "Kufranja", value: "kufranja", city: "ajloun" },
  { label: "Orjan", value: "orjan", city: "ajloun" },
  { label: "Ain Janna", value: "ain_janna", city: "ajloun" },

  // Tafilah areas
  { label: "Tafilah City Center", value: "tafilah_center", city: "tafilah" },
  { label: "Dana", value: "dana", city: "tafilah" },
  { label: "Buseira", value: "buseira", city: "tafilah" },
  { label: "Al-Hasa", value: "al_hasa", city: "tafilah" },
  { label: "Aima", value: "aima", city: "tafilah" },
  { label: "Qadesiyah", value: "qadesiyah_tafilah", city: "tafilah" }
];

export const condition = [
  { label: "Excellent", value: "excellent" },
  { label: "Very Good", value: "very_good" },
  { label: "Good", value: "good" },
  { label: "Fair", value: "fair" },
  { label: "Needs Repair", value: "needs_repair" }
];

export const gender = [
  { label: "Male", value: "male" },
  { label: "Female", value: "female" },
];

export const price = [
  { label: "Free", value: "0" },
  { label: "1 JD", value: "1" },
  { label: "2 JD", value: "2" },
  { label: "3 JD", value: "3" },
  { label: "4 JD", value: "4" },
  { label: "5 JD", value: "5" },
  { label: "7 JD", value: "7" },
  { label: "10 JD", value: "10" },
  { label: "15 JD", value: "15" },
  { label: "20 JD", value: "20" },
  { label: "25 JD", value: "25" },
  { label: "30 JD", value: "30" },
  { label: "40 JD", value: "40" },
  { label: "50 JD", value: "50" },
  { label: "75 JD", value: "75" },
  { label: "100 JD", value: "100" },
  { label: "150 JD", value: "150" },
  { label: "200 JD", value: "200" },
  { label: "250 JD", value: "250" },
  { label: "300 JD", value: "300" },
];

// Helper functions to filter items by category and areas by city
export const getItemsByCategory = (categoryValue) => {
  return items.filter(item => item.category === categoryValue);
};

export const getAreasByCity = (cityValue) => {
  return areas.filter(area => area.city === cityValue);
};

// Helper functions to get labels from values
export const getCategoryLabel = (categoryValue) => {
  if (!categoryValue) return categoryValue;
  const category = categories.find(cat => cat.value === categoryValue);
  return category ? category.label : categoryValue;
};

export const getItemLabel = (itemValue) => {
  if (!itemValue) return itemValue;
  const item = items.find(itm => itm.value === itemValue);
  return item ? item.label : itemValue;
};

export const getCityLabel = (cityValue) => {
  if (!cityValue) return cityValue;
  const city = cities.find(cty => cty.value === cityValue);
  return city ? city.label : cityValue;
};

export const getAreaLabel = (areaValue) => {
  if (!areaValue) return areaValue;
  const area = areas.find(ar => ar.value === areaValue);
  return area ? area.label : areaValue;
};

export const getConditionLabel = (conditionValue) => {
  if (!conditionValue) return conditionValue;
  const cond = condition.find(c => c.value === conditionValue);
  return cond ? cond.label : conditionValue;
};

export const getPriceLabel = (priceValue) => {
  if (!priceValue) return priceValue;
  const pr = price.find(p => p.value === priceValue);
  return pr ? pr.label : `${priceValue} JD`;
};